
services:
  tripwallet-bot:
    build: .
    container_name: tripwallet-ai
    restart: always
    env_file:
      - .env
    dns:
      - 8.8.8.8
      - 8.8.4.4
      - 1.1.1.1
    volumes:
      - ./data:/usr/src/app/data
      - ./logs:/usr/src/app/logs
      - ./.wwebjs_auth:/usr/src/app/.wwebjs_auth
      - ./.wwebjs_cache:/usr/src/app/.wwebjs_cache
